vscode:
  extensions:
    - tshamz.liquid-snippet-include-detection@0.11.0:8DBIPUAlZDV3HC0PTh8pbw==
    - ginfuru.ginfuru-vscode-jekyll-syntax@0.1.0:+V4pMrGcADmecWKXh1JZPw==
    - killalau.vscode-liquid-snippets@1.2.0:jTqWZuR8ggO4IGsESxYfrA==